# Generated by Django 4.2.23 on 2025-08-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSEData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('index_type', models.CharField(choices=[('NIFTY50', 'Nifty 50'), ('FNO', 'F&O')], max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol'], name='trading_nse_symbol_100cf0_idx'), models.Index(fields=['index_type'], name='trading_nse_index_t_3b9a46_idx')],
            },
        ),
    ]
