# Generated by Django 4.2.23 on 2025-08-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_transaction_total_amount_alter_transaction_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holding',
            options={},
        ),
    ]
