# Generated by Django 4.2.23 on 2025-08-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_holding_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='total_amount',
        ),
    ]
