# Generated by Django 4.2.23 on 2025-08-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_transaction_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='My Portfolio', max_length=100),
        ),
    ]
