# Generated by Django 4.2.23 on 2025-08-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_alter_portfolio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='initial_cash',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12),
        ),
    ]
