# Generated by Django 4.2.23 on 2025-08-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_alter_stock_options_stock_day_high_stock_day_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
