# Generated by Django 4.2.23 on 2025-08-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_transaction_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Visible to Users'), ('PRIVATE', 'Hidden from Users')], default='PUBLIC', help_text='Control whether this portfolio is visible to users', max_length=10),
        ),
    ]
