# Generated by Django 5.2.5 on 2025-08-26 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_portfolio_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='trading.portfolio'),
        ),
    ]
