# Generated by Django 4.2.28 on 2026-02-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0013_portfolio_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holding",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="holdingreport",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
