# Generated by Django 5.2.5 on 2025-08-27 09:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('trade_no', models.CharField(db_index=True, max_length=20)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('entry', models.DecimalField(decimal_places=2, max_digits=12)),
                ('main_sl', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Main SL')),
                ('tp1', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tp2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tp3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('waiting', models.BooleanField(default=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
