# Generated by Django 4.2.23 on 2025-08-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='lotsize',
            field=models.IntegerField(default=1, max_length=10),
        ),
    ]
