# Generated by Django 4.2.23 on 2025-08-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_lotsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='lotsize',
            field=models.IntegerField(default=1),
        ),
    ]
